Repository elifesciences/enhanced-preprints-client, pull requests merged in 2022-12, with the labels that each got.

#282 fix tabbed navigation issue.
  src/components/pages/article/article-page.module.scss
Labels: bug

#286 Fix preview build CI and set deployment status correctly
  .github/workflows/build-preview.yaml
Labels: preview

#280 Hide institutions and display author line on narrow viewports
  src/components/atoms/authors/authors.module.scss
  src/components/atoms/authors/authors.test.tsx
  src/components/atoms/authors/authors.tsx
  src/components/atoms/institutions/institutions.module.scss
  src/sass/_typography.scss
Labels: preview

#292 Static page for pdf
  src/components/pages/article/article-page.tsx
  src/pages/reviewed-preprints/[msid]/pdf.page.tsx
Labels: feature, unplanned, preview

#291 Fix unspecified typing in test suite
  src/pages/api/reviewed-preprints.page.test.ts
Labels: bug, unplanned

#295 Fix preview build pipeline to also build the storybook image
  .github/workflows/build-preview.yaml
Labels: preview

#293 Disabled modular css
  next.config.js
  src/components/atoms/abstract/abstract.scss
  src/components/atoms/abstract/abstract.tsx
  src/components/atoms/article-content/article-content.scss
  src/components/atoms/article-content/article-content.tsx
  src/components/atoms/article-flag/article-flag.scss
  src/components/atoms/article-flag/article-flag.tsx
  src/components/atoms/authors/authors.scss
  src/components/atoms/authors/authors.tsx
  src/components/atoms/button/button.scss
  src/components/atoms/button/button.tsx
  src/components/atoms/descriptors/descriptors.scss
  src/components/atoms/descriptors/descriptors.tsx
  src/components/atoms/editors-and-reviewers/editors-and-reviewers.scss
  src/components/atoms/editors-and-reviewers/editors-and-reviewers.tsx
  src/components/atoms/figure/figure.scss
  src/components/atoms/figure/figure.tsx
  src/components/atoms/footer-main/footer-main.scss
  src/components/atoms/footer-main/footer-main.tsx
  src/components/atoms/heading/heading.scss
  src/components/atoms/heading/heading.tsx
  src/components/atoms/institutions/institutions.scss
  src/components/atoms/institutions/institutions.tsx
  src/components/atoms/investors/investors.scss
  src/components/atoms/investors/investors.tsx
  src/components/atoms/jump-to-menu/jump-to-menu.scss
  src/components/atoms/jump-to-menu/jump-to-menu.tsx
  src/components/atoms/modal/modal.scss
  src/components/atoms/modal/modal.tsx
  src/components/atoms/reference-list/reference-list.scss
  src/components/atoms/reference-list/reference-list.tsx
  src/components/atoms/review-content/review-content.scss
  src/components/atoms/review-content/review-content.tsx
  src/components/atoms/sign-up/sign-up.scss
  src/components/atoms/sign-up/sign-up.tsx
  src/components/atoms/title/title.scss
  src/components/atoms/title/title.tsx
  src/components/layouts/default.scss
  src/components/layouts/default.tsx
  src/components/molecules/article-flag-list/article-flag-list.scss
  src/components/molecules/article-flag-list/article-flag-list.tsx
  src/components/molecules/article-status/article-status.scss
  src/components/molecules/article-status/article-status.tsx
  src/components/molecules/author-information-list/author-information-list.scss
  src/components/molecules/author-information-list/author-information-list.tsx
  src/components/molecules/content-header/content-header.scss
  src/components/molecules/content-header/content-header.tsx
  src/components/molecules/contextual-data/contextual-data.scss
  src/components/molecules/contextual-data/contextual-data.tsx
  src/components/molecules/site-header/site-header.scss
  src/components/molecules/site-header/site-header.tsx
  src/components/molecules/timeline/timeline.scss
  src/components/molecules/timeline/timeline.tsx
  src/components/pages/article/article-page.scss
  src/components/pages/article/article-page.tsx
  src/components/pages/article/tabs/figures-tab.tsx
  src/components/pages/article/tabs/fulltext-tab.tsx
  src/components/pages/article/tabs/reviews-tab.tsx
  src/components/pages/error-pages/page-not-found.scss
  src/components/pages/error-pages/page-not-found.tsx
Labels: preview

#298 Display unconfirmed ORCID iD in author information list
  src/components/molecules/author-information-list/author-information-list.scss
  src/components/molecules/author-information-list/author-information-list.test.tsx
  src/components/molecules/author-information-list/author-information-list.tsx
  src/types/author.ts
  src/utils/mocks/authors.ts
Labels: preview
