Repository elifesciences/enhanced-preprints-client, pull requests merged in 2023-02, with the labels that each got.

#351 refactor h1 tag for different sizes on breakpoints
  src/sass/_typography.scss
Labels: preview

#341 Add test for peer review content
  src/components/pages/article/tabs/reviews-tab.test.tsx
  src/utils/mocks/peer-review.ts
Labels: debt

#362 fix up the msid discovery to be based on the param passed by routing
  src/pages/api/reviewed-preprints/[msid].page.ts
Labels: bug

#363 refactor grid so action buttons collapse correctly
  src/components/molecules/article-status/article-status.scss
  src/components/molecules/article-status/article-status.tsx
  src/components/molecules/site-header/site-header.scss
  src/components/molecules/timeline/timeline.scss
  src/sass/_layout.scss
Labels: preview

#373 add link to logo to homepage and remove unwanted padding
  src/components/molecules/site-header/site-header.scss
  src/components/molecules/site-header/site-header.tsx
Labels: preview

#378 Change alignments tabs
  src/components/pages/article/article-page.scss
Labels: preview

#357 Clipboard positioning fix
  src/components/atoms/citation/citation.scss
  src/components/atoms/clipboard/clipboard.scss
  src/components/atoms/clipboard/clipboard.tsx
  src/components/atoms/socials/socials.scss
  src/components/molecules/article-status/article-status.scss
  src/components/molecules/article-status/article-status.tsx
  src/components/molecules/modal/modal.scss
  src/components/molecules/modal/modal.stories.tsx
  src/components/molecules/modal/modal.tsx
Labels: preview

#411 Added new controlled vocabulary word 'valuable'
  src/components/atoms/review-content/review-content.test.tsx
  src/components/atoms/review-content/review-content.tsx
Labels: task
