Repository elifesciences/enhanced-preprints-client, pull requests merged in 2023-10, with the labels that each got.

#1237 make sure we compare a date to a date when checking published dates in the future
  src/utils/generate-article-status.ts
Labels: bug

#1225 Approval workflow
  .github/workflows/pr-coko-approval.yaml
Labels: coko-approved

#1235 Author copyright
  src/components/atoms/copyright/copyright.stories.tsx
  src/components/atoms/copyright/copyright.test.tsx
  src/components/atoms/copyright/copyright.tsx
  src/components/molecules/author-information-list/author-information-list.tsx
Labels: preview, coko-approved

#1275 Evaluation doi
  src/components/atoms/descriptors/descriptors.scss
  src/components/atoms/review-content/review-content.scss
  src/components/atoms/review-content/review-content.stories.tsx
  src/components/atoms/review-content/review-content.test.tsx
  src/components/atoms/review-content/review-content.tsx
  src/components/pages/article/tabs/fulltext-tab.test.tsx
  src/components/pages/article/tabs/fulltext-tab.tsx
  src/components/pages/article/tabs/reviews-tab.tsx
  src/sass/_settings.scss
  src/types/peer-review.ts
  src/utils/mocks/peer-review.ts
Labels: preview, coko-approved

#1308 add new type for reference published date
  src/components/atoms/reference/reference.tsx
  src/components/molecules/modal/modal.stories.tsx
  src/types/reference.ts
  src/utils/mocks/references.ts
Labels: skip-coko-approval

#1309 Switch the client and storybook images around to deliver client faster
  .github/workflows/ci.yaml
Labels: skip-coko-approval

#1310 Handle publishedYear in a reference being optional from server
  src/components/atoms/reference/reference.test.tsx
  src/components/atoms/reference/reference.tsx
  src/components/molecules/modal/modal.stories.tsx
  src/types/reference.ts
  src/utils/mocks/references.ts
Labels: skip-coko-approval

#1300 preprintDoi for 89573v1
  manuscripts.json
Labels: skip-coko-approval

#1317 Add PDFs to manuscripts.json
  manuscripts.json
Labels: coko-approved

#1324 Add 60 PDF links to manuscripts.json
  manuscripts.json
Labels: coko-approved

#1335 Add PDFs for 48 RP versions
  manuscripts.json
Labels: coko-approved
