Repository elifesciences/enhanced-preprints-client, pull requests merged in 2023-11, with the labels that each got.

#1343 Change expected header value of Journal API
  browser-tests/api-reviewed-preprints.spec.ts
  src/pages/api/reviewed-preprints/[msid].page.ts
Labels: coko-approved

#1351 Fix timeline for 90465v1
  manuscripts.json
Labels: coko-approved

#1357 Add 37 PDFs
  manuscripts.json
Labels: coko-approved

#1364 Add 72 PDF links
  manuscripts.json
Labels: coko-approved, skip-coko-approval

#1365 Add 18 PDF URLs
  manuscripts.json
Labels: skip-coko-approval

#1350 Use Prettier as part of Stylelint
  package.json
  src/components/atoms/authors/authors.scss
  src/components/atoms/footer-main/footer-main.scss
  stylelint.config.js
  yarn.lock
Labels: coko-approved

#1371 Pass preview param through to server if we are on a preview URL
  src/pages/reviewed-preprints/[...path].page.tsx
  src/utils/fetch-data.ts
Labels: skip-coko-approval

#1382 Add 17 PDFs
  manuscripts.json
Labels: skip-coko-approval

#1403 Add 19 PDF URLs
  manuscripts.json
Labels: skip-coko-approval

#1411 Add links for 23 PDFs
  manuscripts.json
Labels: skip-coko-approval

#1429 Add 35 PDF links
  manuscripts.json
Labels: skip-coko-approval

#1434 Add another type to support different identifier type
  src/components/molecules/author-information-list/author-information-list.test.tsx
  src/components/molecules/author-information-list/author-information-list.tsx
  src/types/enhanced-article.ts
  src/utils/create-author-id.test.ts
  src/utils/mocks/authors.ts
Labels: skip-coko-approval

#1433 change 'Posted to bioRxiv' to 'Posted to preprint server'
  src/utils/generate-timeline.test.ts
  src/utils/generate-timeline.ts
Labels: skip-coko-approval

#1431 Fix automation so that we load the correct images from the correct place
  docker-compose.automated.yaml
Labels: skip-coko-approval

#1437 fix: also change the link to biorxiv in the timeline
  src/utils/generate-timeline.test.ts
  src/utils/generate-timeline.ts
Labels: skip-coko-approval

#1432 Change 'Revised preprint' to 'Reviewed Preprint' for all article vs
  src/components/atoms/clipboard/clipboard.test.tsx
  src/pages/api/reviewed-preprints.page.test.ts
  src/scripts/cliPublishManuscript.ts
  src/types/article-status.ts
  src/utils/generate-article-status.test.ts
  src/utils/generate-article-status.ts
Labels: skip-coko-approval

#1444 add function to convert roles to display friendly version
  src/components/atoms/editors-and-reviewers/editors-and-reviewers.test.tsx
  src/components/atoms/editors-and-reviewers/editors-and-reviewers.tsx
Labels: skip-coko-approval
