Repository elifesciences/enhanced-preprints-client, pull requests merged in 2023-12, with the labels that each got.

#1383 Generate Sections from ThematicBreak's
  src/types/content.ts
  src/utils/content-to-jsx.test.tsx
  src/utils/content-to-jsx.tsx
Labels: preview, coko-approved

#1465 fix: not filtering content for figures tab in old preview page
  src/pages/preview/[...path].page.tsx
Labels: bug, skip-coko-approval

#1469 fix broken ts in test
  src/pages/api/reviewed-preprints.page.test.ts
Labels: skip-coko-approval

#1472 Fixes for finding image info, stop crashing when we don't have it
  src/utils/content-to-img-info.ts
  src/utils/content-to-jsx.tsx
Labels: skip-coko-approval

#1474 Add links for 90 PDFs
  manuscripts.json
Labels: skip-coko-approval

#1473 Keep the logic when version is same as current
  src/pages/reviewed-preprints/[...path].page.tsx
  src/types/article-status.ts
  src/utils/generate-article-status.test.ts
  src/utils/generate-article-status.ts
Labels: skip-coko-approval

#1490 fix preprintDoi for 93273
  manuscripts.json
Labels: skip-coko-approval

#1509 feat: update 'published' and 'reviewedDate' to use 'firstPublished'
  src/pages/api/reviewed-preprints.page.test.ts
  src/pages/api/reviewed-preprints.page.ts
  src/pages/api/reviewed-preprints/[msid].page.ts
  src/types/reviewed-preprint-snippet.ts
Labels: skip-coko-approval

#1525 upgrade alpine
  Dockerfile
Labels: preview, dependencies

#1526 Upgrade other next components
  package.json
  yarn.lock
Labels: dependencies
