Repository elifesciences/enhanced-preprints-client, pull requests merged in 2024-10, with the labels that each got.

#2152 Encoda author notes
  src/components/atoms/author-list/author-list.scss
  src/components/atoms/author-list/author-list.test.tsx
  src/components/atoms/author-list/author-list.tsx
  src/components/atoms/author-notes/author-notes.scss
  src/components/atoms/author-notes/author-notes.stories.tsx
  src/components/atoms/author-notes/author-notes.test.tsx
  src/components/atoms/author-notes/author-notes.tsx
  src/components/molecules/article-and-author-information/article-and-author-information.tsx
  src/types/author.ts
  src/types/index.ts
  src/types/meta-data.ts
  src/utils/generators/generate-author-id.test.ts
  src/utils/mocks/authors.ts
Labels: preview, skip-coko-approval

#2165 set default namespace during page render to namespace sent with pageProps.siteName
  src/pages/_app.page.tsx
Labels: preview

#2167 Introduce I18nextProvider
  src/components/atoms/assessment/assessment.stories.tsx
  src/components/atoms/assessment/assessment.test.tsx
  src/components/atoms/assessment/assessment.tsx
  src/components/atoms/review-content/review-content.stories.tsx
  src/components/atoms/review-content/review-content.test.tsx
  src/components/atoms/review-content/review-content.tsx
  src/components/atoms/review-process/review-process.stories.tsx
  src/components/atoms/review-process/review-process.test.tsx
  src/components/atoms/review-process/review-process.tsx
  src/components/atoms/socials/socials.stories.tsx
  src/components/atoms/socials/socials.tsx
  src/components/molecules/article-status/article-status.stories.tsx
  src/components/molecules/article-status/article-status.test.tsx
  src/components/molecules/article-status/article-status.tsx
  src/components/molecules/timeline/timeline.stories.tsx
  src/components/molecules/timeline/timeline.test.tsx
  src/components/molecules/timeline/timeline.tsx
  src/components/pages/article/article-page.stories.tsx
  src/components/pages/article/article-page.test.tsx
  src/components/pages/article/article-page.tsx
  src/components/pages/article/tabs/fulltext-tab.test.tsx
  src/components/pages/article/tabs/fulltext-tab.tsx
  src/pages/_app.page.tsx
  src/pages/reviewed-preprints/[...path].page.tsx
Labels: skip-coko-approval

#2157 Move eLife assessment above abstract [elifesciences/enhanced-preprints-issues#1165]
  src/components/atoms/assessment/assessment.scss
  src/components/pages/article/article-page.scss
  src/components/pages/article/tabs/figures-tab.tsx
  src/components/pages/article/tabs/fulltext-tab.test.tsx
  src/components/pages/article/tabs/fulltext-tab.tsx
  src/components/pages/article/tabs/reviews-tab.tsx
Labels: preview

#2178 Surface the publisher name and location in references [elifesciences/enhanced-preprints-issues#814]
  README.md
  src/components/atoms/reference-list/reference-list.test.tsx
  src/components/atoms/reference/reference.test.tsx
  src/components/atoms/reference/reference.tsx
  src/types/reference.ts
  src/utils/mocks/references.ts
Labels: preview, skip-coko-approval
