Repository elifesciences/enhanced-preprints-client, pull requests merged in 2024-05, with the labels that each got.

#1901 use exitZeroOnChanges option to fail a job on unapproved changes
  src/utils/mocks/content.ts
Labels: skip-coko-approval

#1916 Previous version warning
  src/components/atoms/previous-version-warning/previous-version-warning.scss
  src/components/atoms/previous-version-warning/previous-version-warning.stories.tsx
  src/components/atoms/previous-version-warning/previous-version-warning.test.tsx
  src/components/atoms/previous-version-warning/previous-version-warning.tsx
  src/images/icons/previous-warning.svg
Labels: skip-coko-approval

#1917 [#1089]: Make adjustments to presentation of aside content to 250px on wider viewports
  src/components/atoms/related-content/related-content.scss
  src/components/molecules/article-status/article-status.scss
  src/components/molecules/timeline/timeline.scss
  src/sass/_layout.scss
Labels: preview, skip-coko-approval

#1919 [#1088]: Fixing issue with flexbox aside to accommodate optional previous version warning
  src/components/atoms/previous-version-warning/previous-version-warning.scss
  src/components/atoms/related-content/related-content.scss
  src/components/molecules/article-status/article-status.scss
  src/components/molecules/timeline/timeline.scss
  src/sass/_layout.scss
Labels: preview, skip-coko-approval

#1924 [#1088]: Improve presentation of previous version warning
  .husky/_/pre-commit
  src/components/atoms/previous-version-warning/previous-version-warning.scss
  src/components/molecules/article-status/article-status.scss
  src/sass/_layout.scss
Labels: preview, skip-coko-approval

#1928 [#1094]: Add trigger for previous version warning
  src/components/pages/article/article-page.tsx
  src/pages/reviewed-preprints/[...path].page.tsx
  src/types/enhanced-article.ts
  src/types/index.ts
  src/utils/generate-article-status.ts
  src/utils/get-latest-version.test.ts
  src/utils/get-latest-version.ts
  src/utils/mocks/enhanced-article-with-versions.ts
Labels: preview, skip-coko-approval

#1935 [#1097]: Introduce improved timeline component with initial styles
  src/components/molecules/improved-timeline/improved-timeline.scss
  src/components/molecules/improved-timeline/improved-timeline.stories.tsx
  src/components/molecules/improved-timeline/improved-timeline.test.tsx
  src/components/molecules/improved-timeline/improved-timeline.tsx
Labels: skip-coko-approval

#1937 [#1097]: refactor improved-timeline scss
  src/components/molecules/improved-timeline/improved-timeline.scss
Labels: skip-coko-approval

#1936 fix: render placeholder images from local
  src/utils/mocks/content.ts
  src/utils/mocks/placeholder.png
Labels: skip-coko-approval

#1909 feat: add otel instrumentation to next app
  next.config.js
  package.json
  src/instrumentation.page.ts
  yarn.lock
Labels: preview, skip-coko-approval

#1934 feat: build multiplatform builds for previews (and faster builds for master)
  .dockerignore
  .github/workflows/ci.yaml
  .github/workflows/pr-preview-env.yaml
  .yarnrc.yml
  Dockerfile
  package.json
  yarn.lock
Labels: preview, skip-coko-approval

#1939 [#1098]: Refactor article status component to use timeline
  src/components/atoms/previous-version-warning/previous-version-warning.scss
  src/components/molecules/article-status/article-status.scss
  src/components/molecules/article-status/article-status.stories.tsx
  src/components/molecules/article-status/article-status.test.tsx
  src/components/molecules/article-status/article-status.tsx
  src/components/molecules/improved-timeline/improved-timeline.scss
  src/components/molecules/improved-timeline/improved-timeline.tsx
  src/components/pages/article/article-page.stories.tsx
  src/components/pages/article/article-page.test.tsx
  src/components/pages/article/article-page.tsx
  src/pages/reviewed-preprints/[...path].page.tsx
  src/sass/_layout.scss
  src/utils/generate-article-status.test.ts
  src/utils/mocks/index.ts
  src/utils/mocks/timeline.ts
Labels: preview

#1951 [#1099]: Add support for multiple events in improved timeline
  src/components/molecules/article-status/article-status.stories.tsx
  src/components/molecules/article-status/article-status.test.tsx
  src/components/molecules/improved-timeline/improved-timeline.scss
  src/components/molecules/improved-timeline/improved-timeline.stories.tsx
  src/components/molecules/improved-timeline/improved-timeline.test.tsx
  src/components/molecules/improved-timeline/improved-timeline.tsx
  src/images/icons/arrowdown-triangle.svg
  src/images/icons/arrowup-triangle.svg
  src/pages/reviewed-preprints/[...path].page.tsx
  src/sass/_settings.scss
  src/utils/mocks/timeline.ts
Labels: preview, skip-coko-approval
