Repository elifesciences/enhanced-preprints-client, pull requests merged in 2024-03, with the labels that each got.

#1769 Switch backstop.js to use firefox as the visual regression engine
  .github/workflows/ci.yaml
  backstop.json
  backstop_data/bitmaps_reference/backstop_default_Article_Tab_0_document_0_tablet.png
  backstop_data/bitmaps_reference/backstop_default_Figures_Tab_0_document_0_tablet.png
  backstop_data/bitmaps_reference/backstop_default_Reviews_Tab_0_document_0_tablet.png
Labels: skip-coko-approval

#1649 Include google fonts from local bundle using `next/fonts`
  src/pages/_app.page.tsx
  src/pages/_document.page.tsx
  src/sass/_settings.scss
Labels: preview, skip-coko-approval

#1782 [#1029] feat: improve handling of related content from server
  src/i18n.ts
  src/pages/reviewed-preprints/[...path].page.tsx
Labels: skip-coko-approval

#1779 Change Twitter icon to new X Logo
  src/components/atoms/footer-main/footer-main.tsx
  src/images/share/tweet.svg
Labels: preview
